coverage:
  status:
    project:
      default:
        paths: "onecodex/"
        target: auto
        base: auto
        threshold: 2.5%
    patch:
      default:
        target: 0%

ignore:
  - "onecodex/vendored/"
